// src/dashboard/countdown/main.vue
<template>
  <div v-if="countdownRunning && countdownRunning.data != undefined">
    <QInput
      v-model="countdownText"
      :disable="countdownRunning.data"
      label="Czas odliczania"
      outlined
      style="margin-bottom: 15px"
    />
    <div style="display: flex; flex-direction: row; gap: 15px">
      <QBtn
        color="primary"
        @click="startCountdown()"
        :disabled="countdownRunning.data || countdownText.length == 0"
        >Rozpocznij</QBtn
      >
      <QBtn
        color="red"
        @click="stopCountdown()"
        :disabled="!countdownRunning.data"
        >Zatrzymaj</QBtn
      >
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Countdown, CountdownRunning } from "@gsps-trylogia/types/schemas";
import { useHead } from "@vueuse/head";
import { useReplicant } from "nodecg-vue-composable";
import { ref, watch } from "vue";

useHead({ title: "Odliczanie" });

const countdownText = ref("10:00");
const countdown = useReplicant<Countdown>("countdown", "gsps-trylogia");
const countdownRunning = useReplicant<CountdownRunning>(
  "countdownRunning",
  "gsps-trylogia"
);

function startCountdown() {
  nodecg.sendMessage("startCountdown", countdownText.value);
}

function stopCountdown() {
  nodecg.sendMessage("stopCountdown");
}

watch(
  () => countdown?.data,
  (newVal) => {
    if (newVal) {
      countdownText.value = newVal.formatted;
    }
  },
  { immediate: true }
);
</script>

// src/browser/dashboard/countdown.tsx
import { useReplicant } from 'use-nodecg';
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { Button, Grid, TextField } from '@mui/material';
import { Countdown, CountdownRunning } from '../../types/generated';
import { useEffect, useState } from 'react';
import { render } from '../render';

const App = () => {
  const [countdownRunning] = useReplicant<CountdownRunning>('countdownRunning', false);
  const [countdown] = useReplicant<Countdown | undefined>('countdown', undefined);
  const [countdownText, setCountdownText] = useState('10:00');

  useEffect(() => {
    if (typeof countdown === 'undefined') return;

    setCountdownText(countdown.formatted);
  }, [countdown]);

  return (
    <DashboardThemeProvider>
      <TextField
        label="Czas odliczania"
        variant="filled"
        disabled={countdownRunning}
        value={countdownText}
        onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
          setCountdownText(event.target.value);
        }}
        style={{ marginBottom: '15px' }}
        fullWidth
      />
      <Grid container spacing={3}>
        <Grid item xs={6}>
          <Button
            variant="contained"
            onClick={() => {
              nodecg.sendMessage('startCountdown', countdownText);
            }}
            disabled={countdownRunning}>
            Rozpocznij odliczanie
          </Button>
        </Grid>
        <Grid item xs={6}>
          <Button
            variant="contained"
            onClick={() => {
              nodecg.sendMessage('stopCountdown');
            }}
            disabled={!countdownRunning}>
            Zatrzymaj odliczanie
          </Button>
        </Grid>
      </Grid>
    </DashboardThemeProvider>
  );
};

render(<App />);
