// src/dashboard/splits/main.vue
<template>
  <v-app>
    <div style="width: 100%; text-align: center">
      <h2>Obecna gra: {{ currentSplit }}</h2>
    </div>
    <v-simple-table>
      <template v-slot:default>
        <thead>
          <tr>
            <th class="text-left">Gra</th>
            <th class="text-right">+/-</th>
            <th class="text-right">Split Time</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="split in splits" :key="split.name">
            <td>{{ split.name }}</td>
            <td>{{ split.formattedDelta }}</td>
            <td>{{ split.formattedOriginalTime }}</td>
          </tr>
        </tbody>
      </template>
    </v-simple-table>
    <v-btn @click="split" :disabled="phase != 'running'"
      ><template v-if="currentSplit === 'GTA: San Andreas'"
        >Zakończ timer</template
      ><template v-else>Następna gra</template></v-btn
    >
    <v-btn @click="resetSplits">Zresetuj splity</v-btn>
  </v-app>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import type { Timer, Splits } from "@gsps-trylogia/types/schemas";
import { Getter } from "vuex-class";

@Component
export default class extends Vue {
  @Getter readonly timer!: Timer; // from store.ts
  @Getter readonly splits!: Splits;
  @Getter readonly currentSplit!: string;

  get phase() {
    return this.timer.phase;
  }
  async split(): Promise<void> {
    try {
      nodecg.sendMessage('split')
    } catch (err) {
      // catch
    }
  }
  async resetSplits(): Promise<void> {
    try {
      await nodecg.sendMessage("resetSplits");
    } catch (err) {
      // error
    }
  }
}
</script>

// src/browser/dashboard/splits.tsx
import { useReplicant } from 'use-nodecg';
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { CurrentSplit, Splits, Timer } from '../../types/generated';
import {
  Button,
  Grid,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material';
import { render } from '../render';

const App = () => {
  const [splits] = useReplicant<Splits>('splits', []);
  const [timer] = useReplicant<Timer | undefined>('timer', undefined);
  const [currentSplit] = useReplicant<CurrentSplit>('currentSplit', 'GTA III');

  return (
    <DashboardThemeProvider>
      <Typography variant="h4" textAlign="center" gutterBottom>
        Obecna gra: <b>{currentSplit}</b>
      </Typography>
      <TableContainer style={{ marginBottom: '15px' }} component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>
                <b>Gra</b>
              </TableCell>
              <TableCell>
                <b>+/-</b>
              </TableCell>
              <TableCell>
                <b>Czas splita</b>
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {splits.map((split) => (
              <TableRow key={split.name} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
                <TableCell component="th" scope="row">
                  {split.name}
                </TableCell>
                <TableCell>{split.formattedDelta}</TableCell>
                <TableCell>{split.formattedOriginalTime}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      {timer && (
        <Grid container spacing={3}>
          <Grid item xs={6}>
            <Button
              variant="contained"
              onClick={() => {
                nodecg.sendMessage('split');
              }}
              disabled={timer.phase != 'running'}>
              {currentSplit === 'GTA: San Andreas' ? 'Zakończ timer' : 'Następna gra'}
            </Button>
          </Grid>
          <Grid item xs={6}>
            <Button
              variant="contained"
              onClick={() => {
                nodecg.sendMessage('resetSplits');
              }}>
              Zresetuj splity
            </Button>
          </Grid>
        </Grid>
      )}
    </DashboardThemeProvider>
  );
};

render(<App />);
