// src/browser/dashboard/timer.tsx
import { useReplicant } from 'use-nodecg';
import { DashboardThemeProvider } from './components/DashboardThemeProvider';
import { createRoot } from 'react-dom/client';
import { Button, Grid, Typography } from '@mui/material';
import { Timer } from '../../types/generated';

const App = () => {
  const [timer] = useReplicant<Timer | undefined>('timer', undefined);

  return (
    <DashboardThemeProvider>
      <div style={{ textAlign: 'center' }}>
        {timer && (
          <>
            {' '}
            <Typography variant="h3" gutterBottom>
              <b>{timer.time}</b>
            </Typography>
            <Grid style={{ width: '100%' }} container spacing={0} justifyContent="space-between">
              <Grid item xs={0}>
                <Button
                  variant="contained"
                  onClick={() => {
                    if (timer.phase == 'stopped' || timer.phase == 'paused') {
                      nodecg.sendMessage('timerStart');
                    } else if (timer.phase == 'running') {
                      nodecg.sendMessage('timerPause');
                    }
                  }}
                  disabled={timer.phase === 'finished'}>
                  {timer.phase === 'running' ? 'Zapauzuj timer' : 'Rozpocznij timer'}
                </Button>
              </Grid>
              <Grid item xs={0}>
                <Button
                  variant="contained"
                  onClick={() => {
                    nodecg.sendMessage('timerReset', true);
                  }}
                  disabled={timer.phase === 'stopped'}>
                  Resetuj timer
                </Button>
              </Grid>
            </Grid>
          </>
        )}
      </div>
    </DashboardThemeProvider>
  );
};

const container = document.getElementById('root');
const root = createRoot(container!);
root.render(<App />);

// src/dashboard/timer/main.vue
<template>
    <v-app>
        <v-container fluid class="text-center">
            <h1 style="font-size: 48px">{{ timer.time }}</h1>
        </v-container>
        <v-container
            fluid
            class="d-flex text-center"
            style="justify-content: space-between"
        >
            <v-btn
                width="45%"
                @click="startTimer"
                :disabled="phase === 'finished'"
                >{{
                    phase === 'running' ? 'Zapauzuj timer' : 'Rozpocznij timer'
                }}</v-btn
            >
            <v-btn
                width="45%"
                @click="resetTimer"
                :disabled="phase === 'stopped'"
                >Resetuj timer</v-btn
            >
        </v-container>
    </v-app>
</template>

<script lang="ts">
    import { Vue, Component } from 'vue-property-decorator';
    import type {
        Timer
    } from '@gsps-trylogia/types/schemas';
    import { Getter } from 'vuex-class';

    @Component
    export default class extends Vue {
        @Getter readonly timer!: Timer; // from store.ts
        get phase() {
            return this.timer.phase;
        }
        async startTimer(): Promise<void> {
            try {
                if (this.phase === 'stopped' || this.phase === 'paused') {
                    await nodecg.sendMessage('timerStart');
                } else if (this.phase === 'running') {
                    await nodecg.sendMessage('timerPause');
                }
            } catch (err) {
                // catch
            }
        }
        async resetTimer(): Promise<void> {
            try {
                await nodecg.sendMessage('timerReset', true);
            } catch (err) {
                // error
            }
        }
    }
</script>
