// src/browser/graphics/omnibar.tsx
import { render } from '../render';
import styled from 'styled-components';
import { StrictMode, useEffect, useRef, useState } from 'react';
import { SwitchTransition, CSSTransition } from 'react-transition-group';
import { GlobalStyle } from '../global-theme';

const OmnibarContainer = styled.div`
  width: 100%;
  height: 50px;
  background-color: #e6e6e6;
  color: rgb(60, 60, 60);
  justify-content: space-between;
  align-content: space-between;
  align-items: center;
  display: flex;
  flex-direction: row;
`;

const CTADiv = styled.div`
  padding-left: 10px;
  font-size: 24px;
`;

const ClockDiv = styled.div`
  font-size: 34px;
  align-self: flex-end;
  padding-left: 10px;
  padding-right: 10px;
  margin-top: auto;
  margin-bottom: auto;
  text-align: right;
`;

export const App = () => {
  const CTAs = [
    'Dołącz do naszej społeczności na Discordzie na <b class="highlight">gsps.pl/discord</b>!',
    'Jako grupa speedrunnerów GTA, próbujemy właśnie razem ukończyć <b class="highlight">GTA III, Vice City i San Andreas</b> na 100% w jednym podejściu!',
    'Więcej o GSPS (polskim charytatywnym wydarzeniu speedrunningowym) znajdziesz na <b class="highlight">gsps.pl</b>!',
  ];
  let currentCTAIndex = 0;
  const [CTA, setCTA] = useState(CTAs[currentCTAIndex]);
  const CTARef = useRef(null);

  const getClockHTML = () => {
    const date_ob = new Date();
    const hours = ('0' + date_ob.getHours()).slice(-2);
    const minutes = ('0' + date_ob.getMinutes()).slice(-2);
    return `${hours}:${minutes}`;
  };

  const [clock, setClock] = useState(getClockHTML());

  const setNextCTA = () => {
    currentCTAIndex++;
    if (currentCTAIndex >= CTAs.length) {
      currentCTAIndex = 0;
    }
    setCTA(CTAs[currentCTAIndex]);
  };

  useEffect(() => {
    // update clock every half a second
    setInterval(() => {
      setClock(getClockHTML());
    }, 500);

    // update CTA every 10 seconds
    setInterval(() => {
      setNextCTA();
    }, 10000);
  }, []);

  return (
    <StrictMode>
      <GlobalStyle />
      <OmnibarContainer>
        <SwitchTransition mode="out-in">
          <CSSTransition key={CTA} nodeRef={CTARef} appear in timeout={1000} classNames="fade">
            <CTADiv ref={CTARef} dangerouslySetInnerHTML={{ __html: CTA! }} />
          </CSSTransition>
        </SwitchTransition>
        <ClockDiv dangerouslySetInnerHTML={{ __html: clock }} />
      </OmnibarContainer>
    </StrictMode>
  );
};

render(<App />);

// src/graphics/main/components/Omnibar.vue
<template>
  <div>
    <div id="logoDiv">
      <img id="logo" src="../gspsLogo.png" />
    </div>
    <div id="completion">
      <b>Postęp ukończenia obecnej gry:</b> {{ completion }}%
    </div>
    <div
      v-for="(cta, i) in CTAs"
      class="cta"
      :id="'cta-' + i"
      :key="i"
      v-html="cta"
    />
    <div id="clockDiv">
      <span id="clock">{{ clock }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import { Getter } from "vuex-class";
import gsap from "gsap";

@Component
export default class Omnibar extends Vue {
  @Getter readonly completion!: string;

  data() {
    return {
      CTAs: [
        "Dołącz do naszej społeczności na Discordzie na <b>gsps.pl/discord!</b>",
        "Jako grupa speedrunnerów GTA, próbujemy właśnie razem ukończyć <b>GTA III, Vice City i San Andreas</b> na 100% w jednym podejściu!",
        "Więcej o GSPS (polskim charytatywnym wydarzeniu speedrunningowym) znajdziesz na <b>gsps.pl!</b>",
      ],
      clock: "",
      tl: gsap.timeline({ repeat: -1 }),
    };
  }

  getClock(): void {
    var date_ob = new Date();

    let hours = ("0" + date_ob.getHours()).slice(-2);

    let minutes = ("0" + date_ob.getMinutes()).slice(-2);
    this.$data.clock = hours + ":" + minutes;
  }
  mounted() {
    this.getClock();
    setInterval(() => {
      this.getClock();
    }, 1000);

    for (let i = 0; i < this.$data.CTAs.length; i++) {
      this.$data.tl
        .to(`#cta-${i}`, { left: "170px", duration: 2, ease: "power2.out" })
        .to(
          `#cta-${i}`,
          { left: "-1085px", duration: 2, ease: "power2.in" },
          ">6"
        );
    }
  }
}
</script>

<style scoped>
.cta {
  position: absolute;
  top: 27px;
  left: -1085px;
  font-size: 20px;
  color: white;
}

#completion {
  position: absolute;
  top: 5px;
  left: 170px;
  font-size: 20px;
  color: white;
  text-shadow: 2px 2px 8px black;
}

#logoDiv {
  width: 160px;
  height: 66px;
  background-color: #3a008b;
  z-index: 15;
  position: absolute;
}

#logo {
  margin-top: -12px;
  margin-left: -11px;
  width: 115%;
}

#clockDiv {
  position: absolute;
  left: 1759px;
  top: 0px;
  height: 66px;
  width: 161px;
  background-color: #3a008b;
  z-index: 10;
  text-align: center;
  display: flex;
  justify-content: center;
  align-content: center;
  z-index: 15;
}

#clock {
  position: relative;
  color: white;
  top: 1px;
  font-size: 40px;
  font-weight: bold;
}
</style>
