// src/dashboard/splits.jsx
import { Button, Typography, Table, TableContainer, TableBody, TableRow, TableCell, ThemeProvider, TableHead } from '@material-ui/core';
import React from 'react';
import { render } from 'react-dom';
import { useReplicant } from 'use-nodecg';
import { createTheme } from '@material-ui/core/styles';

const Splits = () => {
    const [splits] = useReplicant('splits', []);
    const [currentSplit] = useReplicant('currentSplit');
    const [SCTimer] = useReplicant('timer', '', {namespace: 'nodecg-speedcontrol'});

    const darkTheme = createTheme({
        palette: {
            type: 'dark'
        }
    })

    const splitList = splits.map((split, uuid) => (
        <TableRow key={uuid}>
            <TableCell component="th" scope="row">
                {split.name}
            </TableCell>
            <TableCell align="right">{split.formattedDelta}</TableCell>
            <TableCell align="right">{split.formattedOriginalTime}</TableCell>
        </TableRow>
    ));

    return(
        <ThemeProvider theme={darkTheme}>
            <div style={{textAlign: 'text-center', width: '100%'}}>
                <Typography variant="h5"><b>Obecna gra: </b>{currentSplit}</Typography>
            </div>
            <br/>
            <TableContainer>
                <Table size="small">
                    <TableHead>
                        <TableRow>
                            <TableCell>Gra</TableCell>
                            <TableCell align="right">+/-</TableCell>
                            <TableCell align="right">Split Time</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {splitList}
                    </TableBody>
                </Table>
            </TableContainer>
            <br/>
            <Button disabled={SCTimer.state != 'running'} variant="contained" color="primary" onClick={() => {nodecg.sendMessage('split')}}>{currentSplit === "GTA: San Andreas" ? <>Zakończ timer</> : <>Następna gra</>}</Button>
            <br/>
            <br/>
            <Button variant="contained" color="primary" onClick={() => {nodecg.sendMessage('resetSplits')}}>Zresetuj wszystkie splity</Button>
        </ThemeProvider>
    )
}

render(<Splits/>, document.getElementById("root"))

// src/dashboard/splits/main.vue
<template>
  <v-app>
    <div style="width: 100%; text-align: center">
      <h2>Obecna gra: {{ currentSplit }}</h2>
    </div>
    <v-simple-table>
      <template v-slot:default>
        <thead>
          <tr>
            <th class="text-left">Gra</th>
            <th class="text-right">+/-</th>
            <th class="text-right">Split Time</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="split in splits" :key="split.name">
            <td>{{ split.name }}</td>
            <td>{{ split.formattedDelta }}</td>
            <td>{{ split.formattedOriginalTime }}</td>
          </tr>
        </tbody>
      </template>
    </v-simple-table>
    <v-btn @click="split" :disabled="phase != 'running'"
      ><template v-if="currentSplit === 'GTA: San Andreas'"
        >Zakończ timer</template
      ><template v-else>Następna gra</template></v-btn
    >
    <v-btn @click="resetSplits">Zresetuj splity</v-btn>
  </v-app>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import type { Timer, Splits } from "@gsps-trylogia/types/schemas";
import { Getter } from "vuex-class";

@Component
export default class extends Vue {
  @Getter readonly timer!: Timer; // from store.ts
  @Getter readonly splits!: Splits;
  @Getter readonly currentSplit!: string;

  get phase() {
    return this.timer.phase;
  }
  async split(): Promise<void> {
    try {
      nodecg.sendMessage('split')
    } catch (err) {
      // catch
    }
  }
  async resetSplits(): Promise<void> {
    try {
      await nodecg.sendMessage("resetSplits");
    } catch (err) {
      // error
    }
  }
}
</script>
